### ISSUE TITLE
Server should not know about the secret

### ISSUE THREAD

**Issue by WoLfulus** [bukinoshita/secret#13]
`send a message through a safe, private, and encrypted link`

Just wondering... It's not private  if the server knows its contents, right?

Even with a password, secret contents are being sent to the server without encryption (plain text). Contents should be encrypted on the client-side (browser) and server should not know anything about it.

There must be a way to encode the secret on the client-side, send it to the server already encoded and decode on the client side (when someone tries to read it), that would be a lot better since the server just becomes the channel to access those secrets. (Maybe using asymmetric key encryption? There are some that works on the browser @ https://gist.github.com/jo/8619441)

**Comment by bukinoshita** [comment]
hey @WoLfulus, I was thinking to add back the `WebCrypto API` and encrypt/decrypt the secret on the client-side. Wasn't so sure if I should keep it because of the lack of browser support.

I will create a `staging` env with WebCrypto again to test it.

**Comment by WoLfulus** [comment]
that would be awesome :)
