### ISSUE TITLE
Open source API server

### ISSUE THREAD

**Issue by sihoang** [bukinoshita/secret#16]
Please correct me if I am wrong.  If the API server gets hacked, the hacker will be able to decrypt all the messages.

My questions are
1. Why do we need to store the decryption key on the server?
2. Are there reasons not to open source the API server?

**Comment by bukinoshita** [comment]
>  If the API server gets hacked, the hacker will be able to decrypt all the messages

We encrypt all messages on the browser, so all data is encrypted on server already. 

The hacker will need to decrypt the `passphrase`, which is encrypted as well. And have a password hash to create a key to decrypt all messages.

> Why do we need to store the decryption key on the server?

We don't store the decryption key on the server

> Are there reasons not to open source the API server?

No, I just don't usually open source my APIs
